version: 0.0
os: linux
files:
  - source: TableQ-*-SNAPSHOT.jar
    destination: /home/ec2-user/app/codeDeploy/

#hooks:
#  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
#    - location: execute-deploy.sh
#      timeout: 180