# local 환경
spring:
  profiles: local
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect # H2 Dialect 설정

    defer-datasource-initialization: true