# dev 환경
# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev  # dev 프로파일에서만 적용

  datasource:
    url: jdbc:postgresql://192.168.1.168:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate  # 스키마 자동 변경, 개발 환경에서 주로 사용
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용
    defer-datasource-initialization: true