server:
  port: 80

thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true

# Choose Environment
spring:
  config:
    location: classpath:application-dev.yml