# local 환경
spring:
  config:
    activate:
      on-profile: local  # local 프로파일에서만 적용
  h2:
    console:
      enabled: true  # /h2-console 접속 가능
  datasource:
    url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        ddl-auto: create  # 매번 스키마 생성 (개발/로컬 환경에 적합)
        dialect: org.hibernate.dialect.H2Dialect  # H2 방언 사용
    defer-datasource-initialization: true  # 데이터 소스 초기화를 지연
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
