# 워크플로우 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: amazonlinux-2

    env:
      JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}

    steps:
      - name: 테스트
        run: echo "$JASYPT_PASSWORD 입니다."

      - name: 체크아웃 Github Action
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build --info
        shell: bash